"""
ModusFlow Multi-CLIP Text Encode Node

Advanced text encoding node that supports:
- Individual text inputs for up to 4 CLIPs
- Flux guidance control (optional)
- Automatic CLIP conditioning merging
- Per-CLIP enable/disable controls
"""

import torch
from nodes import CLIPTextEncode, ConditioningSetTimestepRange


class ModusFlowMultiCLIPTextEncode:
    """
    Encode text using multiple CLIP models with individual prompt control.
    Supports Flux guidance for flux-based models.
    """
    
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                # Text inputs for each CLIP
                "text_clip1": ("STRING", {"multiline": True, "default": ""}),
                "text_clip2": ("STRING", {"multiline": True, "default": ""}),
                "text_clip3": ("STRING", {"multiline": True, "default": ""}),
                "text_clip4": ("STRING", {"multiline": True, "default": ""}),
                
                # Enable/disable each CLIP
                "enable_clip1": ("BOOLEAN", {"default": True}),
                "enable_clip2": ("BOOLEAN", {"default": False}),
                "enable_clip3": ("BOOLEAN", {"default": False}),
                "enable_clip4": ("BOOLEAN", {"default": False}),
                
                # Flux guidance settings
                "use_flux_guidance": ("BOOLEAN", {"default": False}),
                "flux_guidance": ("FLOAT", {"default": 3.5, "min": 0.0, "max": 100.0, "step": 0.1}),
            },
            "optional": {
                # Optional CLIP inputs from model loader
                "clip1": ("CLIP",),
                "clip2": ("CLIP",),
                "clip3": ("CLIP",),
                "clip4": ("CLIP",),
                
                # Optional merged CLIP for fallback
                "clip_merged": ("CLIP",),
            }
        }
    
    RETURN_TYPES = ("CONDITIONING",)
    RETURN_NAMES = ("conditioning",)
    FUNCTION = "encode_text"
    CATEGORY = "ModusFlow/Conditioning"
    OUTPUT_NODE = False

    def encode_text(self, text_clip1, text_clip2, text_clip3, text_clip4,
                   enable_clip1, enable_clip2, enable_clip3, enable_clip4,
                   use_flux_guidance, flux_guidance,
                   clip1=None, clip2=None, clip3=None, clip4=None, clip_merged=None):
        """
        Encode text using multiple CLIP models and combine the conditioning.
        """
        
        
        # Collect enabled CLIPs and their corresponding texts
        clip_configs = [
            (clip1, text_clip1, enable_clip1, "CLIP 1"),
            (clip2, text_clip2, enable_clip2, "CLIP 2"),
            (clip3, text_clip3, enable_clip3, "CLIP 3"),
            (clip4, text_clip4, enable_clip4, "CLIP 4"),
        ]
        
        conditionings = []
        text_encoder = CLIPTextEncode()
        
        # Process each CLIP
        for clip, text, enabled, label in clip_configs:
            if enabled and clip is not None and text.strip():
                try:
                    # Encode text with this CLIP using the standard encode method
                    # This ensures all required metadata is generated by ComfyUI's CLIP encoder
                    conditioning_result = text_encoder.encode(clip, text)
                    conditioning = conditioning_result[0]
                    
                    # Debug: Show metadata from fresh encoding
                    if isinstance(conditioning, list) and len(conditioning) > 0:
                        cond_data = conditioning[0]
                        if isinstance(cond_data, list) and len(cond_data) > 1 and isinstance(cond_data[1], dict):
                            metadata_keys = list(cond_data[1].keys())
                    
                    conditionings.append(conditioning)
                except Exception as e:
                    import traceback
                    traceback.print_exc()
            elif enabled and clip is None:
                pass
            elif enabled and not text.strip():
                pass
        
        # Fallback to merged CLIP if no individual CLIPs were used
        if not conditionings and clip_merged is not None:
            # Use the first non-empty text
            fallback_text = text_clip1 or text_clip2 or text_clip3 or text_clip4 or ""
            if fallback_text.strip():
                try:
                    conditioning_result = text_encoder.encode(clip_merged, fallback_text)
                    conditioning = conditioning_result[0]
                    conditionings.append(conditioning)
                except Exception as e:
                    pass
        
        # Validate we have at least one conditioning
        if not conditionings:
            raise ValueError("No conditioning generated! Please enable at least one CLIP and provide text.")
        
        # For multi-CLIP: concatenate conditioning lists instead of averaging
        # This preserves all metadata and lets the model handle multiple CLIPs properly
        if len(conditionings) == 1:
            final_conditioning = conditionings[0]
        else:
            # Concatenate all conditioning entries instead of averaging
            # This is the correct way to handle multiple CLIPs - keep them separate
            final_conditioning = []
            for cond in conditionings:
                if isinstance(cond, list):
                    final_conditioning.extend(cond)
            
            # Debug: Show metadata from each entry
            for idx, cond_entry in enumerate(final_conditioning):
                if isinstance(cond_entry, list) and len(cond_entry) > 1 and isinstance(cond_entry[1], dict):
                    metadata_keys = list(cond_entry[1].keys())
        
        # Apply Flux guidance if enabled
        # This needs to be applied to each conditioning entry in the list
        if use_flux_guidance:
            try:
                final_conditioning = self._apply_flux_guidance_to_list(final_conditioning, flux_guidance)
            except Exception as e:
                import traceback
                traceback.print_exc()
        
        
        return (final_conditioning,)
    
    def _merge_conditionings(self, conditionings):
        """
        Merge multiple conditioning tensors by averaging.
        Preserves all metadata from the first conditioning.
        """
        try:
            # Extract conditioning tensors and metadata
            cond_tensors = []
            pooled_outputs = []
            base_params = {}  # Store all params from first conditioning
            
            for idx, cond in enumerate(conditionings):
                if isinstance(cond, list) and len(cond) > 0:
                    # cond is typically [[tensor, {params}]]
                    cond_data = cond[0]
                    if isinstance(cond_data, list) and len(cond_data) >= 1:
                        cond_tensors.append(cond_data[0])
                        
                        # Collect all parameters from first conditioning
                        if idx == 0 and len(cond_data) > 1 and isinstance(cond_data[1], dict):
                            base_params = cond_data[1].copy()
                        
                        # Check for pooled output to average
                        if len(cond_data) > 1 and isinstance(cond_data[1], dict):
                            if 'pooled_output' in cond_data[1]:
                                pooled_outputs.append(cond_data[1]['pooled_output'])
            
            # Average the conditioning tensors
            if cond_tensors:
                # Stack and average
                stacked = torch.stack(cond_tensors, dim=0)
                averaged = torch.mean(stacked, dim=0)
                
                # Average pooled outputs if they exist
                if pooled_outputs:
                    stacked_pooled = torch.stack(pooled_outputs, dim=0)
                    averaged_pooled = torch.mean(stacked_pooled, dim=0)
                    base_params['pooled_output'] = averaged_pooled
                
                # Return with all original metadata preserved
                return [[averaged, base_params]]
            else:
                # Fallback: return first conditioning
                return conditionings[0]
        except Exception as e:
            # Fallback: return first conditioning
            return conditionings[0]
    
    def _apply_flux_guidance_to_list(self, conditioning_list, guidance):
        """
        Apply Flux guidance scale to all conditioning entries in a list.
        Preserves all existing metadata for each entry.
        """
        try:
            if not isinstance(conditioning_list, list):
                return conditioning_list
            
            result = []
            for cond_entry in conditioning_list:
                if isinstance(cond_entry, list) and len(cond_entry) >= 1:
                    # Deep copy tensor
                    tensor_copy = cond_entry[0].clone()
                    
                    # Deep copy all metadata
                    if len(cond_entry) > 1 and isinstance(cond_entry[1], dict):
                        params_copy = {}
                        for key, value in cond_entry[1].items():
                            # Deep copy tensors, shallow copy everything else
                            if isinstance(value, torch.Tensor):
                                params_copy[key] = value.clone()
                            else:
                                params_copy[key] = value
                        # Add/update guidance
                        params_copy['guidance'] = guidance
                    else:
                        params_copy = {'guidance': guidance}
                    
                    result.append([tensor_copy, params_copy])
                else:
                    result.append(cond_entry)
            
            return result
        except Exception as e:
            import traceback
            traceback.print_exc()
            return conditioning_list
    
    def _apply_flux_guidance(self, conditioning, guidance):
        """
        Apply Flux guidance scale to conditioning.
        Flux guidance modifies the conditioning strength.
        Preserves all existing metadata.
        DEPRECATED: Use _apply_flux_guidance_to_list instead.
        """
        try:
            # Apply guidance scale to the conditioning tensor
            if isinstance(conditioning, list) and len(conditioning) > 0:
                cond_data = conditioning[0]
                if isinstance(cond_data, list) and len(cond_data) >= 1:
                    # Deep copy to avoid modifying the original
                    tensor_copy = cond_data[0].clone()
                    
                    # Deep copy all metadata
                    if len(cond_data) > 1 and isinstance(cond_data[1], dict):
                        params_copy = {}
                        for key, value in cond_data[1].items():
                            # Deep copy tensors, shallow copy everything else
                            if isinstance(value, torch.Tensor):
                                params_copy[key] = value.clone()
                            else:
                                params_copy[key] = value
                        # Add/update guidance
                        params_copy['guidance'] = guidance
                    else:
                        params_copy = {'guidance': guidance}
                    
                    return [[tensor_copy, params_copy]]
            
            return conditioning
        except Exception as e:
            return conditioning


# Node class mappings
NODE_CLASS_MAPPINGS = {
    "ModusFlowMultiCLIPTextEncode": ModusFlowMultiCLIPTextEncode
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "ModusFlowMultiCLIPTextEncode": "ModusFlow Multi-CLIP Text Encode"
}