class ModusFlowShowText:
    """
    A node that displays text strings in the ComfyUI interface.
    Useful for viewing prompts generated by LLMs or other text-generating nodes.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "text": ("STRING", {"forceInput": True}),
            },
            "hidden": {
                "unique_id": "UNIQUE_ID",
                "extra_pnginfo": "EXTRA_PNGINFO",
            },
        }

    INPUT_IS_LIST = True
    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("text",)
    FUNCTION = "show_text"
    OUTPUT_NODE = True
    OUTPUT_IS_LIST = (True,)
    CATEGORY = "ModusFlow/Utilities"

    def show_text(self, text, unique_id=None, extra_pnginfo=None):
        """
        Displays the input text and passes it through as output.

        Args:
            text: The text string(s) to display
            unique_id: Hidden parameter for node identification
            extra_pnginfo: Hidden parameter for workflow metadata

        Returns:
            Dictionary with UI display data and the text as output
        """
        # Update the node's widget values in the workflow metadata if available
        if unique_id is not None and extra_pnginfo is not None:
            if isinstance(extra_pnginfo, list) and isinstance(extra_pnginfo[0], dict) and "workflow" in extra_pnginfo[0]:
                workflow = extra_pnginfo[0]["workflow"]
                node = next(
                    (x for x in workflow["nodes"] if str(x["id"]) == str(unique_id[0])),
                    None,
                )
                if node:
                    node["widgets_values"] = [text]

        return {"ui": {"text": text}, "result": (text,)}
